# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };

  fileSystems."/boot/firmware" = {
    device = "systemd-1";
    fsType = "autofs";
  };

  fileSystems."/mnt/photon" = {
    device = "/dev/disk/by-uuid/823aa65e-d3e9-4f93-9cb3-d7e8955bb274";
    fsType = "btrfs";
    options = [ "nofail" "x-systemd.automount" "x-systemd.device-timeout=10s" ];
  };

  fileSystems."/mnt/squid" = {
    device = "/dev/disk/by-uuid/fedaf19b-45b8-4694-bcfc-c8739e64d262";
    fsType = "btrfs";
    options = [ "nofail" "x-systemd.automount" "x-systemd.device-timeout=10s"];
  };

  fileSystems."/export/photon" = {
    device = "/mnt/photon";
    options = [ "bind" "nofail" "x-systemd.device-timeout=10s"];
  };

  fileSystems."/export/squid" = {
    device = "/mnt/squid";
    options = [ "bind" "nofail" "x-systemd.device-timeout=10s"];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth248fcf1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
